### ISSUE TITLE
Feature request: batch processing options

### ISSUE THREAD

**Issue by axur-delmeria** [Lazza/RecuperaBit#35] opened 2018-04-28 10:40 UTC
I'm trying to recover some files, and somehow Recuperabit found over 20k partitions, 1.4k of which are said to be recoverable.

Partition 57 lists a lot (maybe all) of the files, but I cannot restore certain files--said files are very large (>5GB) Outlook PSTs, and had CRC errors on the original disk--I'm running Recuperabit on a disk image created by ddrescue. I want to find out if any of the other 1.4k recoverable partitions contain enough data to recover the files I need, but I find that running csv, locate, or bodyfile to peruse each of the 1.4k partitions is quite tedious.

Which is why I'm wondering if some form of batch processing is possible. 

For example, a FOR loop where the input is the list of recoverable partitions, and the output is a csv or bodyfile for each said partition (e.g. partition 1 would output 1.csv or 1.bodyfile, partition 2 would create 2.csv or 2.bodyfile, etc.). Then I can use grep or other text processors to find the files I need. 

Alternatively, expand the locate command so that it can:
1. check all recoverable partitions (with option for other/non-recoverable partitions, which might be useful in certain scenarios)
2. output the results to a text file for later perusal.

**Comment by Lazza** [comment] 2018-04-28 10:46
This looks like an exact duplicate of #8. I have already explained there why doing this is a bad idea.

The purpose of RecuperaBit is not to recover any useless leftover from previous disk defrag, it is to clearly separate partitions so you can only focus on the good stuff.

**Comment by Lazza** [comment] 2021-01-02 17:56
I am going to close this because the discussion is evolving in an interesting way on issue #43.

**Closed by Lazza** 2021-01-02 17:56 UTC
