### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 35: ordinal not in range(128)

### ISSUE THREAD

**Issue by rnissl** [Lazza/RecuperaBit#26] opened 2017-10-25 07:41 UTC
Hi,

I want to recover files from a 300 GB drive which seems to have been quickformated under Windows 10.

Some comments on excerpt of the attached console output:
> INFO:root:13786 partitions found.
I wouldn't expect that number of partions but maybe this is how the program works.

> Partition #10869 -> Partition (NTFS, 297.26 GB, 288715 files, Recoverable, Offset: 1730560, Offset (b): 886046720, Sec/Clus: 8, MFT offset: 8022016, MFT mirror offset: 1730576)
Among the recoverable partions, this one sounds promising.

When I try to recover files from that partition (see last 20 lines of attached file), I get the error message mentioned as subject and the program exits.

Is there a chance to get this fixed?
How can I assist further?

Thanks in advance.

Bye.
[recuperabit.zip](https://github.com/Lazza/RecuperaBit/files/1413671/recuperabit.zip)

**Comment by Lazza** [comment] 2017-10-30 16:25
Is this a duplicate of #14?

**Comment by rnissl** [comment] 2017-10-30 18:26
Hmm, maybe.

The locale was set like that, when running the program for the above report:

corei7:~ # locale
LANG=POSIX
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

So I did an

export LANG=de_DE.UTF-8

which changed locale like that:

corei7:~ # locale
LANG=de_DE.UTF-8
LC_CTYPE=de_DE.UTF-8
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

But the program aborted again with the same error.

**Comment by rnissl** [comment] 2017-11-01 11:50
After adding the two lines mentioned in #14, I was able to recover many files.
Thanks for your product and support!

**Comment by Lazza** [comment] 2017-11-02 23:34
What lines did you change, exactly? RecuperaBit should run just fine in any **UTF-8 enabled** terminal.

**Comment by rnissl** [comment] 2017-11-03 13:36
If added these lines:

reload(sys)
sys.setdefaultencoding('utf-8')

But I'm not used to python.

**Comment by Lazza** [comment] 2017-11-09 22:05
Mmm... I see. The fact is, it should already work correctly on UTF-8 enabled terminals. Could you tell me more about your configuration?

**Closed by Lazza** 2017-11-09 22:05 UTC
Labels: duplicate
