### ISSUE TITLE
Large drives hang with no log or restart mode

### ISSUE THREAD

**Issue by beaster99** [Lazza/RecuperaBit#66] opened 2019-12-29 09:44 UTC
I have repeatedly had the same issue with scanning a large NTFS drive (2TB) and the scanner stopping at the same location each time 

INFO:root:Found NTFS file record at sector **2239712054**

At this point there is no means to move forward or back.
The save file is not written to disk so I cant leverage this.
There is no log file that I am aware of so I cannot see the state of the python script and what is causing it to be in what looks like a suspended state.
The drive light is still flashing so it appears the disk is still in use, however short of trying to locate the file IO stream, there is little information about what is happening.

Checking the Process IO to see what disk access is active on the pypy Process ID

"this has been trimmed"

> iotop
> Current DISK READ: 36.07 M/s | Current DISK WRITE: 0.00 B/s
>
> TID   PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO
> 8165 be/4    root        36.18 M/s      0.00 B/s          0.00 %         71.98 %  
>
> COMMAND
> pypy ./main.py -s //root/recupera.2019.12.29.sav -o //media/beaster/Seagate /dev/sdb3

Checking the Process ID to see what file IO are opened.

> root@staticus://var/log# lsof -p 8165
> lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/124/gvfs
>       Output information may be incomplete.
> lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
>       Output information may be incomplete.
> lsof: WARNING: can't stat() fuse file system /run/user/1000/doc
>       Output information may be incomplete.
> COMMAND  PID USER   FD   TYPE DEVICE      SIZE/OFF   NODE NAME
> pypy    8165 root  cwd    DIR   0,52            10  42344 /home/beaster/Downloads/RecuperaBit- master
> pypy    8165 root  rtd    DIR   0,27            25     34 /
> pypy    8165 root  txt    REG   0,27         14488 535912 /usr/lib/pypy/bin/pypy-c
> pypy    8165 root  mem    REG   0,27      14537024  29992 /usr/lib/locale/locale-archive
> pypy    8165 root  mem    REG   0,27        158288  61734 /usr/lib/x86_64-linux-gnu/libpthread-> 2.30.so
> pypy    8165 root  mem    REG   0,27        100888  60478 /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
> pypy    8165 root  mem    REG   0,27        192032  59634 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.1
> pypy    8165 root  mem    REG   0,27         35128  45038 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
> pypy    8165 root  mem    REG   0,27         43544  60070 /usr/lib/x86_64-linux-gnu/libcrypt-2.30.so
> pypy    8165 root  mem    REG   0,27         40040  61916 /usr/lib/x86_64-linux-gnu/librt-2.30.so
> pypy    8165 root  mem    REG   0,27        182560  45010 /usr/lib/x86_64-linux-gnu/libexpat.so.1.6.9
> pypy    8165 root  mem    REG   0,27       1369352  61276 /usr/lib/x86_64-linux-gnu/libm-2.30.so
> pypy    8165 root  mem    REG   0,27       2954080  60078 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
> pypy    8165 root  mem    REG   0,27        593856  62092 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
> pypy    8165 root  mem    REG   0,27        108928  62688 /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
> pypy    8165 root  mem    REG   0,27         74848  59904 /usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4
> pypy    8165 root  mem    REG   0,27         18816  60186 /usr/lib/x86_64-linux-gnu/libdl-2.30.so
> pypy    8165 root  mem    REG   0,27         14848  62304 /usr/lib/x86_64-linux-gnu/libutil-2.30.so
> pypy    8165 root  mem    REG   0,27       2025032  59906 /usr/lib/x86_64-linux-gnu/libc-2.30.so
> pypy    8165 root  mem    REG   0,27      71493512 536606 /usr/lib/pypy/bin/libpypy-c.so
> pypy    8165 root  mem    REG   0,27        187376  24858 /usr/lib/x86_64-linux-gnu/ld-2.30.so
> pypy    8165 root    0u   CHR  136,0           0t0      3 /dev/pts/0
> pypy    8165 root    1u   CHR  136,0           0t0      3 /dev/pts/0
> pypy    8165 root    2u   CHR  136,0           0t0      3 /dev/pts/0
> pypy    8165 root    3r   BLK   8,19 0x12cf589c000    488 /dev/sdb3
> 

Checking if the save file has any information updated indicates this is not written out to disk until the scan is completed.
> root@staticus://var/log# ls -Flash //root/recupera.2019.12.29.sav 
> /usr/bin/ls: cannot access '//root/recupera.2019.12.29.sav': No such file or directory

At this point there is no real path forwards to debug the state of the script, it seems like it needs a log file argument (assuming logging is actually invoked in the script, having not yet read the code itself)

**Comment by Lazza** [comment] 2020-01-14 20:44
I think this is almost a duplicate of #46, please also see my comment there. 👍 

In particular, **currently the script prints when it _finds_ something.** If it's reading an "empty" area it would seem it's stuck. This is surely not a neat aspect and it should be changed.

Let's continue the discussion on #46 to avoid spreading useful comments across different issues.

**Closed by Lazza** 2020-01-14 20:44 UTC

**Comment by Lazza** [comment] 2020-01-14 20:52
Sorry, I meant #34 and not only #46.
